### ISSUE TITLE
error: implicit declaration of function ‘hdhomerun_discover_find_devices_custom’ [-Werror=implicit-function-declaration]

### ISSUE THREAD

**Issue by dony71** [pakar/tvheadend-hdhomerun#15]
while compile get this error
src/input/mpegts/tvhdhomerun/tvhdhomerun.c: In function ‘tvhdhomerun_discovery_timer_cb’:
src/input/mpegts/tvhdhomerun/tvhdhomerun.c:320:3: error: implicit declaration of function ‘hdhomerun_discover_                         find_devices_custom’ [-Werror=implicit-function-declaration]
   int numDevices = hdhomerun_discover_find_devices_custom(0,
   ^
cc1: all warnings being treated as errors
Makefile:357: recipe for target '/home/pi/Downloads/tvheadend-hdhomerun/build.linux/src/input/mpegts/tvhdhomer                         un/tvhdhomerun.o' failed
make: *** [/home/pi/Downloads/tvheadend-hdhomerun/build.linux/src/input/mpegts/tvhdhomerun/tvhdhomerun.o] Erro                         r 1

using latest libhdhomerun_20161117.tgz

**Comment by pakar** [comment]
Hello,
This repo is not maintained at the moment with any later releases of libhdhomerun. Please use the official repo of tvheadend at https://github.com/tvheadend/tvheadend
